import SideBar from "../../components/SideBar";

import { MENU_ITEMS } from "./constant/menu";

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function AdminDashboardLayout({ children }) {
  return (
    <div className="flex flex-row gap-5">
      <div className="flex flex-row gap-5">
        <header>
          <SideBar menuItems={MENU_ITEMS} />
        </header>
        <main className="max-w-[854px] min-h-screen no-scrollbar">
          {children}
        </main>
      </div>
    </div>
  );
}
