import PageHeading from "@/app/components/PageHeading";
import SideBar from "../../components/SideBar";

import { MENU_ITEMS } from "./constant/menu";

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

const AdminDashboardLayout = ({ children }) => {
  return (
    <div className="flex flex-row bg-[#EEECEC]">
      <header className="flex basis-1/6 ">
        <SideBar menuItems={MENU_ITEMS} />
      </header>
      <main className="flex  basis-5/6 ">
        <div className="w-full flex-col h-screen scrollbar-hide overflow-y-auto">
          {children}
        </div>
      </main>
    </div>
  );
};

export default AdminDashboardLayout;
