import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../app/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DWP ITERA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
